### 测试用户登录功能
POST http://127.0.0.1:5000/user/login/
Content-Type: application/json

{
    "name":"baizhan",
    "pwd":"123"
}


### 测试用户注册功能
POST http://127.0.0.1:5000/user/users/
Content-Type: application/json

{
    "name":"sq110",
    "pwd":"123456111",
    "real_pwd":"123456111",
    "email":"111@qq.com",
    "phone":"18803181117",
    "nick_name":"孙权",
    "role_id":3
}

### 测试登录装饰器是否有用
GET http://127.0.0.1:5000/user/test/
token:eyJhbGciOiJIUzI1NiIsIn9.eyJpZCI6MSwiZXhwIjoxNjcyMzIwNzY5LjMzMzMwNTh9.nZLeFOnELN0tvfldviOkbsghUpvhPCaxut2kukV2gl0

### 测试获取菜单
GET http://127.0.0.1:5000/menu/menus/

### 测试根据ID获取单个用户
GET http://127.0.0.1:5000/user/user/3/

### 测试获取用户列表
GET http://127.0.0.1:5000/user/users/

### 测试用户修改功能
PUT http://127.0.0.1:5000/user/user/6/
Content-Type: application/json

{
    "email":"666@qq.com",
    "phone":"17766666777",
    "nick_name":"吕小布",
    "role_id":1
}


### 测试用户删除功能
DELETE  http://127.0.0.1:5000/user/user/2/

### 测试用户重置密码功能
GET http://127.0.0.1:5000/user/reset_pwd/1/