"""empty message

Revision ID: 103e80a78cf6
Revises: 3c1485f803f5
Create Date: 2023-01-06 22:22:39.551254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '103e80a78cf6'
down_revision = '3c1485f803f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_menus',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('path', sa.String(length=32), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pid'], ['t_menus.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_menus')
    # ### end Alembic commands ###
