"""empty message

Revision ID: 473dbec4f281
Revises: 0f09907ba9f5
Create Date: 2023-03-02 21:56:31.662071

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '473dbec4f281'
down_revision = '0f09907ba9f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_product_attr',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.Column('aid', sa.Integer(), nullable=True),
    sa.Column('val', sa.String(length=256), nullable=True),
    sa.Column('_type', sa.Enum('static', 'dynamic'), nullable=True),
    sa.ForeignKeyConstraint(['aid'], ['t_attribute.id'], ),
    sa.ForeignKeyConstraint(['pid'], ['t_product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('product_attr')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_attr',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('pid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('aid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('val', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('_type', mysql.ENUM('static', 'dynamic'), nullable=True),
    sa.ForeignKeyConstraint(['aid'], ['t_attribute.id'], name='product_attr_ibfk_1'),
    sa.ForeignKeyConstraint(['pid'], ['t_product.id'], name='product_attr_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('t_product_attr')
    # ### end Alembic commands ###
