"""empty message

Revision ID: 93897e0756e5
Revises: f06a96d791bc
Create Date: 2023-01-15 21:02:38.062931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93897e0756e5'
down_revision = 'f06a96d791bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 't_roles', ['role_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('role_id')

    # ### end Alembic commands ###
