"""empty message

Revision ID: c2b3d628a162
Revises: eda3c306b2ec
Create Date: 2023-03-02 18:12:57.368829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2b3d628a162'
down_revision = 'eda3c306b2ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_attr',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.Column('aid', sa.Integer(), nullable=True),
    sa.Column('val', sa.String(length=255), nullable=True),
    sa.Column('_type', sa.Enum('static', 'dynamic'), nullable=True),
    sa.ForeignKeyConstraint(['aid'], ['t_attribute.id'], ),
    sa.ForeignKeyConstraint(['pid'], ['t_product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_picture',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('path', sa.String(length=255), nullable=True),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pid'], ['t_product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_picture')
    op.drop_table('product_attr')
    # ### end Alembic commands ###
