"""empty message

Revision ID: c580cc9f015c
Revises: 93897e0756e5
Create Date: 2023-01-31 16:24:31.979104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c580cc9f015c'
down_revision = '93897e0756e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_roles_menus',
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('menus_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['menus_id'], ['t_menus.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['t_roles.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_roles_menus')
    # ### end Alembic commands ###
