"""empty message

Revision ID: d38f7573b25c
Revises: c2b3d628a162
Create Date: 2023-03-02 18:14:25.755663

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd38f7573b25c'
down_revision = 'c2b3d628a162'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_attr', schema=None) as batch_op:
        batch_op.alter_column('val',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=256),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_attr', schema=None) as batch_op:
        batch_op.alter_column('val',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###
